### ISSUE TITLE
Unable to deploy Laravel app on Google app engine with bitfumes/laravel-multiauth package

### ISSUE THREAD

**Issue by ZahedShaikh** [bitfumes/laravel-multiauth#97]
**Describe the bug**
This package work fine on localhost, but not get deploy on Google Cloud app engine.

```php
ERROR: build step 1 "gcr.io/gae-runtimes/php73_app_builder:php73_20200223_7_3_14_RC00" failed: step exited with non-zero status: 1
ERROR
Finished Step #1 - "builder"
Step #1 - "builder": IOError: [Errno 2] No such file or directory: '""/output'
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__/ftl/common/ftl_error.py", line 58, in UserErrorHandler
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__.py", line 57, in main
Step #1 - "builder":   File "/usr/local/bin/ftl.par/__main__.py", line 65, in <module>
Step #1 - "builder":     exec code in run_globals
Step #1 - "builder":   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
Step #1 - "builder":     "__main__", fname, loader, pkg_name)
Step #1 - "builder":   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
Step #1 - "builder": Traceback (most recent call last):
Step #1 - "builder": error: `composer_install` returned code: 1
Step #1 - "builder": 
Step #1 - "builder": Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
Step #1 - "builder": > @php artisan package:discover --ansi
Step #1 - "builder": > Illuminate\Foundation\ComposerScripts::postAutoloadDump
Step #1 - "builder": Generating optimized autoload files
Step #1 - "builder":   - Installing nunomaduro/collision (v4.1.3): Downloading (100%)
Step #1 - "builder":   - Installing facade/ignition-contracts (1.0.0): Downloading (100%)
Step #1 - "builder":   - Installing filp/whoops (2.7.1): Downloading (100%)
Step #1 - "builder":   - Installing laravel/tinker (v2.3.0): Downloading (100%)
Step #1 - "builder":   - Installing psy/psysh (v0.10.2): Downloading (100%)
....
....
```

**Laravel Version**
Tried on laravel 5.8, 6.0, and 7 as well

**To Reproduce**
1. composer install bitfumes/laravel-multiauth
2. gcloud app deploy

**Expected behavior**
It should deploy

**Screenshots**

**Desktop (please complete the following information):**
 - Google App Engine

**Additional context**

**Comment by sarthaksavvy** [comment]
Hey, your error doesn't tell anything about this package!
